# Created By Kuldeep Pandit
# 09/02/2023

name: getx_code_architecture
description: getx code architecture
publish_to: 'https://github.com/PanditKuldeep/Getx-Code-Architecture/'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #get: ^4.6.5
  get: ^4.6.1
  dartz: ^0.10.1
  retrofit: ^3.3.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  logger: ^1.1.0
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^3.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  synchronized: ^3.0.1
  intl: ^0.18.0
  encrypt: ^5.0.1
  json_annotation: ^4.8.0
  font_awesome_flutter: ^10.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
      - assets/images/
      - assets/env/